# Generated by Django 2.1 on 2019-05-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_id', models.CharField(max_length=255)),
                ('cj', models.CharField(max_length=255)),
                ('cx', models.CharField(max_length=255)),
                ('nk', models.CharField(max_length=255)),
                ('js', models.CharField(max_length=255)),
                ('wt', models.CharField(max_length=255)),
                ('time', models.DateField()),
                ('ms', models.TextField()),
            ],
            options={
                'db_table': 'Complaint',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128, unique=True)),
                ('user_password', models.CharField(max_length=256)),
                ('time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_form',
            },
        ),
    ]
